spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/audit
    username: ${vault.database.username}
    password: ${vault.database.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
