spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/audit
    username: # Leave blank, Vault will populate this
    password: # Leave blank, Vault will populate this
    driver-class-name: org.postgresql.Driver
